apiVersion: v1
kind: Service
metadata:
  namespace: cervejaria
  name: redis-svc-node
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      nodePort: 30002
      targetPort: 6379
