apiVersion: v1
kind: Service
metadata:
  namespace: cervejaria
  name: redis-svc-cluster
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
