apiVersion: v1
kind: Service
metadata:
  namespace: cervejaria
  name: cervejaria-svc
spec:
  selector:
    app: cervejaria
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30010
      #targetPort: 8081
      port: 8080