apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-deploy
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appLabel}}
  template:
    metadata:
      labels:
        app:  {{.Values.appLabel}}
    spec:
      containers:
        - name: {{.Release.Name}}
          {{include "cervejaria.readinessProbe" . | indent 10}}
          {{include "cervejaria.livenessProbe" . | indent 10}}
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
      restartPolicy: Always


