apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{.Release.Name}}-svc
spec:
  selector:
    app: {{.Values.appLabel}}
  type: {{.Values.service.type}}
  ports:
    - protocol: TCP
      {{- if (eq .Values.service.type "NodePort")}}
      nodePort: {{.Values.service.nodePort}}
      {{- end}}
      targetPort: {{.Values.service.targetPort}}
      port: {{.Values.service.port}}