name: Hello
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Colocar Em Produção
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Build Com Maven
        run: mvn clean package -DskipTest
