name: Hello
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Colocar Em Produção
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Build Com Maven
        run: mvn -Dmaven.test.skip=true clean package
      - name: Copiando Artefato
        run: cp target/cervejaria-acme-0.0.1-SNAPSHOT.jar docker/cervejaria-acme-0.0.1-SNAPSHOT.jar
      - name: Build da Imagem
        run: docker build -t cervejaria-acme:latest ./docker
      - name: Criando a Tag
        run: docker tag  cervejaria-acme:latest leogloriainfnet/cervejaria-acme:latest
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Push da Imagem
        run: docker push ${{ secrets.DOCKERHUB_USER}}/cervejaria-acme:latest
      - name: Restartando Deploy
        run: kubectl rollout restart deploy cervejaria-deploy
      - name: Aguardar Deploy atualizar
        run: kubectl rollout status deploy cervejaria-deploy